title: "Net-Archive"
description: "Net-Archive is a site where I put docs that provide guidance on using software."
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
include_footer: false

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Posts"
    url: /posts/
  - title: "Docs"
    url: /docs/


# Author (optional)
author:
  name: "ernugraha"
  avatar: "/assets/images/avatar.png"

# Defaults (required for layout to work properly)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

collections:
  pages:
    output: true
    permalink: /:path/

atom_feed:
  hide: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ernugrahaDev"
    - label: "About"
      url: "/about/"

  text: "© 2025 ernugraha. Built with Jekyll"

# Custom CSS
sass:
  style: compressed

# Make sure to include the custom CSS file
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      css: "/assets/css/custom.css"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      css: "/assets/css/custom.css"
