source "https://rubygems.org"

gem "jekyll"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-paginate"
gem "jekyll-lunr-js-search"
gem "github-pages"
gem "liquid-md5"
gem "jekyll-tagging"
gem "kramdown-parser-gfm"
gem "webrick"
